apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: java-microservice
  template:
    metadata:
      labels:
        app.kubernetes.io/name: java-microservice
    spec:
      containers:
      - name: java-microservice-container
        image: 870033244562.dkr.ecr.us-east-2.amazonaws.com/assessment_q_2:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "728Mi"
            cpu: "500m"
