apiVersion: v1
kind: Service
metadata:
  name: "service-java-microservice"
  namespace: default
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "alb"
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: java-microservice
